### ISSUE TITLE
Game balance

### ISSUE THREAD

**Issue by TheSniperFan** [Omnomios/DynamicBulwarks#69]
Hello, we've been playing this mod on our server and noticed that the scenario isn't really balanced all that well.

There were rounds where all we fought were increasingly difficult infantry squads, and from one wave to the next it switched to a huge infantry squad, an APC and a main battle tank. You get these crazy difficulty spikes and I think the scenario should have a more gradual difficulty increase.

I've just been hired to work on a game, so I don't exactly have the time to study your code and figure out where to integrate it cleanly (I'm also not all that familiar with Arma 3 scripting to begin with). However, I do know an algorithm that can be used to balance the game properly and I could provide a description/pseudo-code, if you're interested and don't already have something planned.

**Comment by thatParadox** [comment]
Hey, thanks for the feedback! It shouldn't jump from just infantry to 2 armored vehicles. After wave 10 - 15 there's a chance for 1 vehicle to spawn, and at least one should spawn in that time. It's possible that the vehicle AI got stuck so it got cleanup up by out scripts that check for stuck AI (the cleanup has been made less aggressive in 1.5 beta 4).

At wave 13 Vipers are added, so that might have been the infantry increase you're talking about? 

It sounds to me like you may have been in a position or something that was glitching the AI movement and a lot of the were getting cleaned up by the scripts checking for stuck AI. Then something changed and all of a sudden the AI were able to progress without getting stuck.

I will take a look at the code and double check that everything I have said is accurate. There has been feedback about the arrival of tanks. I'm going to see if there's a way to randomly select cars with turrets to ease into armor.

I'll leave this open for now in case I've misunderstood anything you have said. Thanks again for the feedback! Keep it coming!!

**Comment by TheSniperFan** [comment]
Same thing happened again. It's worth noting that it happens quite late. I don't remember exactly, but I think it was always around wave 20. So what might have happened is that 1 vehicle was possible, but the RNG just went "no vehicle, no vehicle, no vehicle, no vehicle" until 2 vehicles were available.

I think the vehicles should ease in more. It should start with those unarmored pickup trucks with guns on their beds and end with main battle tanks (and AA tanks, since they're nasty against infantry).

It would also be better if the addition of a vehicle reduced the amount of infantry that wave. It shouldn't RNG between 20 infantrymen and 20 infantrymen + a tank.

**Comment by thatParadox** [comment]
In the latest build (check the discord general chat) we've got armed cars coming in first now. There's a check for the maximum number of waves since armour now as well so you will get armour by wave 14 and you will have gotten a least a couple of armed cars beforehand. 

We'll keep your other feedback in mind, thanks :)
